version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: iluvcoffee
      POSTGRES_PASSWORD: iluvcoffee
      POSTGRES_DB: iluvcoffee
    ports:
      - 5432:5432